// One-off (re-runnable): give every profile that has NO avatar the generated one the app would
// have given it, and point its profile at it.
//
// WHY. Until 2026-09-27 a profile's first avatar was only ever generated by the Account page,
// but a Google sign-in and an email-confirmation link both land on the homepage, so a new user
// who went straight to making and saving art never got one, and their designs sat in the public
// gallery under the hexagon placeholder. The app now generates one on whichever page its owner
// is signed in on (AuthContext), so anyone who comes back heals by themselves. This reaches the
// ones who have not come back.
//
// WHAT IT WRITES, and nothing else: for each profile whose avatar_url is null, one JPEG at
// avatars/<user_id>/avatar.jpg and that profile's avatar_url. Exactly the path, format and URL
// shape the app's own uploadMyAvatar writes (src/lib/profiles.js), so the result is
// indistinguishable from an avatar the app made -- and AuthorBadge's self-hosted check, which
// decides whether a gallery byline shows the image at all, accepts it. A profile that already
// has an avatar_url of any kind is never touched.
//
// THE IMAGE is the app's real generator, not a port: ../src/render/generateAvatar.js and
// renderAvatar.js, bundled in memory by esbuild for the same reason build.js exists (Node cannot
// resolve their extensionless imports), drawn through shim.js's canvas. Checked against Chromium
// when this was written: the same seed renders to within 3-4/255 per channel, anti-aliasing
// only. The seed is derived from the user id, so a dry run's previews are exactly what a real
// run uploads, and a re-run makes the same image for the same person.
//
// SAFETY
//   --dry-run   renders every avatar and writes previews to avatar-backfill-preview/ (gitignored)
//               without touching Supabase. Look at them first.
//   --limit=N   only the first N profiles in the listed order (most saved designs first, so a
//               canary run lands on someone visible in the gallery). Re-running continues with
//               the rest -- only profiles still without an avatar are ever selected.
//   A profile is re-checked immediately before its upload, and its avatar_url is only set if it
//   is STILL null, so an avatar the app makes for someone mid-run is never replaced.
//   Every run records what it did in avatar-backfill-<timestamp>.json (gitignored), rewritten
//   after each profile, and afterwards re-reads every profile it wrote and fetches every image
//   through its public URL.
//   --undo=<file> sets avatar_url back to null for the profiles that file says were written,
//               and ONLY where avatar_url is still exactly the URL written then -- someone who
//               has since regenerated keeps theirs. Storage objects are never deleted: the path
//               is shared with the app's own avatar, so an object may be someone's current one.
//
// Needs the project's SERVICE ROLE key: it reads every profile and writes into every user's
// avatar folder, which the owner-only RLS on both would otherwise refuse. Taken from the
// environment, or from the repo's .env.local like scripts/backfill-geometry-presence.mjs.
//
// Usage (from render-service/, after `npm install` there):
//   node backfill-avatars.mjs --dry-run
//   node backfill-avatars.mjs --limit=1
//   node backfill-avatars.mjs
//   node backfill-avatars.mjs --undo=avatar-backfill-<timestamp>.json [--dry-run]
import './shim.js';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { loadImage } from '@napi-rs/canvas';
import { createClient } from '@supabase/supabase-js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..');

// Must match the app: AuthContext's AVATAR_SIZE and toBlob(..., 'image/jpeg', 0.9), and
// profiles.js's bucket/path. @napi-rs/canvas takes JPEG quality as 0-100, not 0-1.
const AVATAR_SIZE = 256;
const JPEG_QUALITY = 90;
const AVATAR_BUCKET = 'avatars';
const PREVIEW_DIR = path.join(HERE, 'avatar-backfill-preview');
const PAGE = 1000;

// --- arguments -----------------------------------------------------------------------------
// Strict on purpose: this writes to production, and a mistyped --dry-run that fell through to a
// real run is the one mistake that cannot be taken back by re-running.
const argv = process.argv.slice(2);
const DRY_RUN = argv.includes('--dry-run');
let LIMIT = null;
let UNDO = null;
for (const arg of argv) {
  if (arg === '--dry-run') continue;
  if (arg.startsWith('--limit=')) {
    LIMIT = Number(arg.slice('--limit='.length));
    if (!Number.isInteger(LIMIT) || LIMIT < 1)
      fail(2, `--limit needs a positive integer, got ${JSON.stringify(arg)}`);
    continue;
  }
  if (arg.startsWith('--undo=')) {
    UNDO = arg.slice('--undo='.length);
    if (!UNDO) fail(2, '--undo needs the path of a file this script wrote');
    continue;
  }
  fail(
    2,
    `Unknown argument ${JSON.stringify(arg)}. Expected --dry-run, --limit=N or --undo=<file>.`
  );
}
if (UNDO && LIMIT !== null) fail(2, '--limit does not apply to --undo.');

// --- environment ---------------------------------------------------------------------------
const envPath = path.join(REPO, '.env.local');
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
}
const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  fail(
    2,
    'Set SUPABASE_URL (or VITE_SUPABASE_URL) and SUPABASE_SERVICE_ROLE_KEY, in the environment or .env.local.'
  );
}
// The public anon/publishable key reads profiles perfectly well (they are world-readable), so a
// dry run with it looks healthy, and a real run then fails at every single upload.
const jwtRole = key => {
  try {
    return JSON.parse(Buffer.from(key.split('.')[1], 'base64url').toString()).role;
  } catch {
    return null;
  }
};
if (SERVICE_ROLE_KEY.startsWith('sb_publishable_') || jwtRole(SERVICE_ROLE_KEY) === 'anon') {
  fail(
    2,
    'SUPABASE_SERVICE_ROLE_KEY is the public anon/publishable key; this needs the service role key.'
  );
}
let PROJECT;
try {
  PROJECT = new URL(SUPABASE_URL).origin;
} catch {
  fail(2, `SUPABASE_URL is not a URL: ${JSON.stringify(SUPABASE_URL)}`);
}
// AuthorBadge renders a byline's avatar only if its URL starts with the app's own
// `${VITE_SUPABASE_URL}/storage/v1/object/public/avatars/`. Every URL written is checked
// against the same prefix, so nothing lands that the gallery would refuse to show.
const SELF_HOSTED_PREFIX = `${PROJECT}/storage/v1/object/public/${AVATAR_BUCKET}/`;

// shim.js defines `window` and `document`, so supabase-js believes it is in a browser and would
// go looking for a session in `window.location`. A service-role client has no session to find.
const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false }
});

function fail(code, message) {
  console.error(message);
  process.exit(code);
}

const short = id => id.slice(0, 8);
const nameOf = p => p.display_name || p.username || '(no name)';

// PostgREST caps a response (1000 rows on Supabase by default), so read in pages rather than
// trusting one request to hold the whole table.
async function readAll(table, columns) {
  const rows = [];
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await supabase
      .from(table)
      .select(columns)
      .order('id')
      .range(from, from + PAGE - 1);
    if (error) throw new Error(`reading ${table}: ${error.message}`);
    rows.push(...data);
    if (data.length < PAGE) return rows;
  }
}

// --- the generator -------------------------------------------------------------------------
async function loadAvatarLib() {
  const result = await build({
    stdin: {
      contents: [
        "export { generateAvatar, AVATAR_GENERATOR_VERSION } from '../src/render/generateAvatar.js';",
        "export { default as renderAvatar } from '../src/render/renderAvatar.js';",
        "export { makeRng } from '../src/render/prng.js';"
      ].join('\n'),
      resolveDir: HERE,
      sourcefile: 'backfill-avatars-entry.js'
    },
    bundle: true,
    format: 'esm',
    platform: 'node',
    write: false,
    logLevel: 'silent'
  });
  const code = result.outputFiles[0].text;
  return import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
}

// randomSeed()'s format (8 base36 characters), but derived from the user id instead of
// Math.random -- the one deliberate difference from the app, and the reason a dry run's
// previews are the images a real run uploads.
function seedFor(lib, userId) {
  const rng = lib.makeRng(`avatar-backfill:${userId}`);
  let seed = '';
  for (let i = 0; i < 8; i++) seed += Math.floor(rng() * 36).toString(36);
  return seed;
}

function renderJpeg(lib, seed) {
  const canvas = lib.renderAvatar(lib.generateAvatar(seed, AVATAR_SIZE));
  const jpeg = canvas.toBuffer('image/jpeg', JPEG_QUALITY);
  canvas.width = 0;
  canvas.height = 0;
  if (!jpeg?.length) throw new Error(`the avatar canvas produced no image for seed ${seed}`);
  return jpeg;
}

// --- undo ----------------------------------------------------------------------------------
async function undo(file) {
  // The "To undo" line prints a bare file name, which lives next to this script; accept it from
  // wherever the script is run.
  const found = [path.resolve(file), path.join(HERE, file)].find(f => fs.existsSync(f));
  if (!found) fail(2, `No such record: ${file}`);
  const record = JSON.parse(fs.readFileSync(found, 'utf8'));
  if (record.project !== PROJECT) {
    fail(
      2,
      `${path.basename(file)} was written against ${record.project}, but this is ${PROJECT}.`
    );
  }
  const written = (record.profiles || []).filter(p => p.status === 'written');
  console.log(
    `${written.length} profile(s) were written by the run in ${path.basename(file)}.` +
      (DRY_RUN ? ' (dry run -- nothing will change)' : '')
  );
  let reverted = 0;
  let kept = 0;
  for (const p of written) {
    const { data: row, error } = await supabase
      .from('profiles')
      .select('avatar_url')
      .eq('id', p.id)
      .maybeSingle();
    if (error) throw new Error(`reading profile ${p.id}: ${error.message}`);
    if (!row || row.avatar_url !== p.url) {
      console.log(
        `KEEP    ${short(p.id)}  ${p.name}  -- ` +
          (row ? 'avatar changed since the backfill, left as it is' : 'profile no longer exists')
      );
      kept++;
      continue;
    }
    if (DRY_RUN) {
      console.log(`WOULD REVERT  ${short(p.id)}  ${p.name}`);
      reverted++;
      continue;
    }
    const { data, error: updateError } = await supabase
      .from('profiles')
      .update({ avatar_url: null })
      .eq('id', p.id)
      .eq('avatar_url', p.url)
      .select('id');
    if (updateError) throw new Error(`reverting profile ${p.id}: ${updateError.message}`);
    if (data.length) {
      console.log(`REVERTED  ${short(p.id)}  ${p.name}`);
      reverted++;
    } else {
      console.log(
        `KEEP    ${short(p.id)}  ${p.name}  -- avatar changed while this ran, left as it is`
      );
      kept++;
    }
  }
  console.log(`\nDone. ${reverted} ${DRY_RUN ? 'would be ' : ''}reverted, ${kept} kept.`);
  process.exit(0);
}

// --- backfill ------------------------------------------------------------------------------
async function main() {
  if (UNDO) return undo(UNDO);

  const profiles = await readAll('profiles', 'id, username, display_name, avatar_url, created_at');
  if (profiles.length === 0) {
    // The table can never really be empty (every account has a row), so this is the wrong
    // project or key -- refuse rather than report a clean run.
    fail(1, 'No profiles came back. Wrong project URL or key? Refusing to report a clean run.');
  }
  const designs = await readAll('designs', 'id, user_id');
  const designCount = new Map();
  for (const d of designs) designCount.set(d.user_id, (designCount.get(d.user_id) || 0) + 1);

  // Sign-in provider, for the report only (it is what tells a missed Google sign-up from an
  // email one). Not needed for anything else, so a failure here is not fatal.
  const provider = new Map();
  try {
    for (let page = 1; ; page++) {
      const { data, error } = await supabase.auth.admin.listUsers({ page, perPage: PAGE });
      if (error) throw error;
      for (const u of data.users) provider.set(u.id, u.app_metadata?.provider || '?');
      if (data.users.length < PAGE) break;
    }
  } catch (err) {
    console.warn(`(Could not read sign-in providers: ${err.message} -- continuing without them.)`);
  }

  const withAvatar = profiles.filter(p => p.avatar_url);
  const foreign = withAvatar.filter(p => !p.avatar_url.startsWith(SELF_HOSTED_PREFIX));
  let candidates = profiles
    .filter(p => !p.avatar_url)
    .sort(
      (a, b) =>
        (designCount.get(b.id) || 0) - (designCount.get(a.id) || 0) ||
        String(a.created_at).localeCompare(String(b.created_at))
    );

  console.log(
    `${profiles.length} profiles: ${withAvatar.length} have an avatar, ${candidates.length} have none.`
  );
  if (foreign.length) {
    // Left alone deliberately -- the app only ever replaces a MISSING avatar -- but worth
    // knowing about: AuthorBadge shows the placeholder for these on public pages.
    console.log(
      `${foreign.length} of those avatar URLs ${foreign.length === 1 ? 'is' : 'are'} not this ` +
        `project's own storage (the gallery shows the placeholder for them); not touched: ` +
        foreign.map(p => short(p.id)).join(', ')
    );
  }
  if (candidates.length === 0) {
    console.log('\nNothing to do.');
    process.exit(0);
  }
  if (LIMIT !== null && LIMIT < candidates.length) {
    console.log(`--limit=${LIMIT}: this run covers the first ${LIMIT}; re-run for the rest.`);
    candidates = candidates.slice(0, LIMIT);
  }

  // Render everything BEFORE writing anything, so a broken environment fails with nothing half
  // done.
  const lib = await loadAvatarLib();
  const plan = candidates.map(p => {
    const seed = seedFor(lib, p.id);
    return { profile: p, seed, jpeg: renderJpeg(lib, seed) };
  });

  console.log('');
  for (const { profile: p } of plan) {
    const created = String(p.created_at).slice(0, 10);
    console.log(
      `  ${short(p.id)}  ${nameOf(p).padEnd(24)}  ${String(provider.get(p.id) || '?').padEnd(6)}  ` +
        `${String(designCount.get(p.id) || 0).padStart(3)} design(s)  joined ${created}`
    );
  }

  if (DRY_RUN) {
    // Emptied first, so the folder only ever shows what THIS run would upload.
    fs.rmSync(PREVIEW_DIR, { recursive: true, force: true });
    fs.mkdirSync(PREVIEW_DIR, { recursive: true });
    for (const { profile: p, jpeg } of plan)
      fs.writeFileSync(path.join(PREVIEW_DIR, `${p.id}.jpg`), jpeg);
    console.log(
      `\nDry run -- nothing written to Supabase. The ${plan.length} avatar(s) a real run would ` +
        `upload are in ${path.relative(process.cwd(), PREVIEW_DIR) || PREVIEW_DIR}/, named by user id.`
    );
    process.exit(0);
  }

  const recordPath = path.join(
    HERE,
    `avatar-backfill-${new Date().toISOString().replace(/[:.]/g, '-')}.json`
  );
  const record = {
    project: PROJECT,
    avatarGeneratorVersion: lib.AVATAR_GENERATOR_VERSION,
    startedAt: new Date().toISOString(),
    profiles: plan.map(({ profile: p, seed }) => ({
      id: p.id,
      name: nameOf(p),
      seed,
      path: `${p.id}/avatar.jpg`,
      url: null,
      status: 'pending'
    }))
  };
  const save = () => fs.writeFileSync(recordPath, JSON.stringify(record, null, 2));
  save();
  console.log(`\nRecording this run in ${path.basename(recordPath)}\n`);

  let written = 0;
  let skipped = 0;
  let failed = 0;
  for (let i = 0; i < plan.length; i++) {
    const { profile: p, jpeg } = plan[i];
    const entry = record.profiles[i];
    try {
      // Re-read just before writing: someone signing in while this runs gets an avatar from
      // the app, and theirs wins.
      const { data: now, error: readError } = await supabase
        .from('profiles')
        .select('avatar_url')
        .eq('id', p.id)
        .maybeSingle();
      if (readError) throw new Error(`re-reading the profile: ${readError.message}`);
      if (!now || now.avatar_url) {
        const why = now ? 'got an avatar before its turn' : 'profile no longer exists';
        entry.status = `skipped: ${why}`;
        console.log(`SKIP  ${short(p.id)}  ${nameOf(p)}  -- ${why}`);
        skipped++;
        continue;
      }

      const { error: uploadError } = await supabase.storage
        .from(AVATAR_BUCKET)
        .upload(entry.path, jpeg, { contentType: 'image/jpeg', upsert: true });
      if (uploadError) throw new Error(`upload: ${uploadError.message}`);

      // Same URL shape as uploadMyAvatar: the path never changes, so `v` is what makes a
      // browser that cached an earlier image at this path fetch the new one.
      const { data: urlData } = supabase.storage.from(AVATAR_BUCKET).getPublicUrl(entry.path);
      const url = `${urlData.publicUrl}?v=${Date.now()}`;
      if (!url.startsWith(SELF_HOSTED_PREFIX)) {
        throw new Error(
          `public URL ${url} is not under ${SELF_HOSTED_PREFIX}; the gallery would not show it`
        );
      }

      const { data: updated, error: updateError } = await supabase
        .from('profiles')
        .update({ avatar_url: url })
        .eq('id', p.id)
        .is('avatar_url', null)
        .select('id');
      if (updateError) throw new Error(`profile update: ${updateError.message}`);
      if (updated.length === 0) {
        // The app gave them one between the re-read and this write. Their profile keeps its own
        // URL; the image at the shared path is now this one, which is still a generated avatar.
        entry.status = 'skipped: got an avatar while this ran';
        console.log(`SKIP  ${short(p.id)}  ${nameOf(p)}  -- got an avatar while this ran`);
        skipped++;
        continue;
      }
      entry.url = url;
      entry.status = 'written';
      console.log(`OK    ${short(p.id)}  ${nameOf(p)}`);
      written++;
    } catch (err) {
      entry.status = `failed: ${err.message}`;
      console.error(`FAIL  ${short(p.id)}  ${nameOf(p)}  -- ${err.message}`);
      failed++;
    } finally {
      save();
    }
  }

  // Verify through the same doors a visitor uses: the stored profile row, and the image at its
  // public URL.
  const done = record.profiles.filter(e => e.status === 'written');
  let bad = 0;
  if (done.length) {
    // In chunks: every id rides in the query string.
    const stored = new Map();
    for (let i = 0; i < done.length; i += 100) {
      const { data: rows, error } = await supabase
        .from('profiles')
        .select('id, avatar_url')
        .in(
          'id',
          done.slice(i, i + 100).map(e => e.id)
        );
      if (error) throw new Error(`re-reading written profiles: ${error.message}`);
      for (const r of rows) stored.set(r.id, r.avatar_url);
    }
    for (const e of done) {
      const problems = [];
      if (stored.get(e.id) !== e.url)
        problems.push(`stored avatar_url is ${JSON.stringify(stored.get(e.id))}`);
      try {
        const res = await fetch(e.url);
        const type = res.headers.get('content-type') || '';
        if (!res.ok) problems.push(`image URL answered ${res.status}`);
        else if (!type.startsWith('image/jpeg'))
          problems.push(`image URL served ${type || 'no content type'}`);
        else {
          const img = await loadImage(Buffer.from(await res.arrayBuffer()));
          if (img.width !== AVATAR_SIZE || img.height !== AVATAR_SIZE) {
            problems.push(
              `image is ${img.width}x${img.height}, expected ${AVATAR_SIZE}x${AVATAR_SIZE}`
            );
          }
        }
      } catch (err) {
        problems.push(`image URL could not be read: ${err.message}`);
      }
      if (problems.length) {
        console.error(`VERIFY FAILED  ${short(e.id)}  ${e.name}  -- ${problems.join('; ')}`);
        e.verified = false;
        bad++;
      } else {
        e.verified = true;
      }
    }
  }
  record.finishedAt = new Date().toISOString();
  save();

  console.log(
    `\nDone. ${written} written, ${skipped} skipped, ${failed} failed.` +
      (done.length
        ? ` Verified ${done.length - bad} of ${done.length} through their public URLs.`
        : '')
  );
  console.log(`Record: ${path.basename(recordPath)}`);
  if (written)
    console.log(`To undo:  node backfill-avatars.mjs --undo=${path.basename(recordPath)}`);
  // Explicit exit: supabase-js holds the event loop open (see backfill-thumbnails.mjs).
  process.exit(failed || bad ? 1 : 0);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
