// GENERATED by scripts/build-mockup-style-groups.mjs -- do not edit by hand.
//
// generator_mockup_id -> the style group that id belongs to, per product. v1 stamps this id on
// every mockup photo it returns, primary and extra alike, and it is stable across tasks -- so it is
// the only thing that says which group an untyped primary came from. Read the builder's header for
// why that matters and how the table is learned.
//
// MODEL_GROUPS_BY_PRODUCT names the on-model group each product's ids were learned for. It is what
// gates asking for that group at all, and what tells the Edge Function which photos to label "on
// model" without restating the tier patterns in Deno.
//
// MOCKUP_STYLE_VIEWS is the view each id actually SHOWS, read from Printful's own filename (which is
// honest where the placement key is not -- see the builder). It names the on-model shots, and only
// those: the flats keep the placement-derived names they have always had, so this cannot reorder or
// relabel a single photo the filmstrip already carried.
//
// PER_VARIANT_MOCKUP_PRODUCTS lists the products Printful photographs ONE VARIANT AT A TIME, so a
// preview may not be shared between two variants that happen to print from the same file. It is the
// restricted_to_variants set, refreshed from the catalog on every run of the builder.
//
// A product missing from MODEL_GROUPS_BY_PRODUCT is never asked for an on-model group, so it keeps
// exactly the two-group filmstrip it has today. An id missing from a product's entry sorts last.
// Both degradations are deliberate: neither can reorder the flats.

export const MOCKUP_STYLE_GROUPS: Record<string, Record<string, string>> = {
  "83": {
    "7225": "Default",
    "7226": "Default",
    "7227": "Default",
    "7228": "Default",
    "7229": "Default",
    "7230": "Default",
    "99475": "Default",
    "99496": "Default",
    "99502": "Default",
    "99504": "Default"
  },
  "257": {
    "963": "Men's",
    "964": "Men's",
    "965": "Men's",
    "966": "Men's",
    "7173": "Flat",
    "7174": "Flat",
    "27339": "Men's 5",
    "27340": "Men's 5",
    "27341": "Men's 5"
  },
  "261": {
    "3437": "Flat",
    "3438": "Flat",
    "26024": "Women's",
    "26025": "Women's",
    "26305": "Women's 3",
    "26306": "Women's 3",
    "26307": "Women's 3",
    "26308": "Women's 3"
  },
  "274": {
    "1107": "Default",
    "1108": "Default",
    "1109": "Default",
    "8645": "Standing",
    "8646": "Product details"
  },
  "320": {
    "2291": "Men's",
    "2292": "Men's",
    "2295": "Men's",
    "2296": "Men's",
    "11466": "Flat",
    "11467": "Flat",
    "14525": "Men's 3",
    "14526": "Men's 3",
    "14527": "Men's 3",
    "14528": "Men's 3",
    "51583": "Product details"
  },
  "388": {
    "6307": "Men's",
    "6308": "Men's",
    "6309": "Men's",
    "6310": "Men's",
    "11462": "Flat",
    "11463": "Flat",
    "31581": "Men's",
    "32479": "Product details"
  },
  "390": {
    "6331": "Men's",
    "6332": "Men's",
    "6333": "Men's",
    "6334": "Men's",
    "13633": "Flat",
    "13634": "Flat",
    "54243": "Product details"
  },
  "420": {
    "8020": "Flat",
    "8021": "Flat",
    "8022": "Flat",
    "8023": "Flat",
    "8113": "Men's 2",
    "8114": "Men's 2",
    "8115": "Men's 2",
    "8116": "Men's",
    "8117": "Men's",
    "8118": "Men's"
  },
  "458": {
    "11615": "Flat",
    "11617": "Flat",
    "11618": "Flat",
    "11619": "Flat",
    "11620": "Flat",
    "11621": "Flat",
    "11663": "Men's",
    "11664": "Men's",
    "11665": "Men's",
    "11666": "Men's",
    "11758": "Men's 2",
    "11759": "Men's 2",
    "11760": "Men's 2",
    "11761": "Men's 2"
  },
  "604": {
    "22364": "Flat",
    "22368": "Flat",
    "22443": "Women's",
    "22444": "Women's",
    "22445": "Men's",
    "22446": "Men's",
    "22453": "Men's",
    "22481": "Women's"
  },
  "615": {
    "22544": "Flat",
    "22634": "Flat",
    "22635": "Men's",
    "22637": "Men's",
    "22705": "Men's",
    "22706": "Men's",
    "23674": "Product details"
  },
  "630": {
    "23262": "Flat",
    "23276": "Flat",
    "23280": "Flat",
    "23346": "Product details",
    "23347": "Product details",
    "23348": "Product details",
    "23355": "Lifestyle 2",
    "23356": "Lifestyle 2",
    "23357": "Lifestyle 2"
  },
  "654": {
    "26051": "Flat",
    "26052": "Flat",
    "26054": "Flat",
    "26111": "Product details",
    "26116": "Product details",
    "26127": "Flat",
    "26128": "Flat",
    "26155": "Men's",
    "26156": "Men's",
    "26157": "Men's",
    "26158": "Men's",
    "26159": "Men's",
    "26161": "Men's",
    "26162": "Men's",
    "26163": "Men's",
    "26164": "Men's",
    "26165": "Men's",
    "26176": "Women's",
    "26177": "Women's",
    "26178": "Women's",
    "26179": "Women's",
    "26180": "Women's",
    "26181": "Women's",
    "26182": "Women's",
    "26183": "Women's",
    "26200": "Flat",
    "26201": "Flat",
    "26226": "Flat"
  },
  "693": {
    "30425": "Flat",
    "30426": "Flat",
    "30428": "Product details",
    "30430": "Product details",
    "30435": "Men's",
    "30436": "Men's",
    "30438": "Men's"
  },
  "717": {
    "32252": "Flat",
    "32253": "Flat",
    "32347": "Product details",
    "32364": "Men's",
    "32365": "Men's"
  },
  "744": {
    "39513": "Flat",
    "39520": "Flat",
    "39539": "Product details",
    "39560": "Product details",
    "39574": "Men's",
    "39575": "Men's",
    "39576": "Men's",
    "39628": "Product details",
    "45262": "Product details"
  },
  "784": {
    "51113": "Flat",
    "51116": "Flat",
    "51119": "Product details",
    "51135": "Men's",
    "51139": "Men's",
    "51142": "Men's",
    "51145": "Men's"
  },
  "801": {
    "57206": "Flat",
    "57214": "Flat",
    "57252": "Men's",
    "57260": "Men's",
    "57268": "Product details",
    "73655": "Product details",
    "73663": "Product details",
    "73671": "Product details"
  }
};

export const MODEL_GROUPS_BY_PRODUCT: Record<string, string> = {
  "257": "Men's 5",
  "261": "Women's 3",
  "274": "Standing",
  "320": "Men's 3",
  "388": "Men's",
  "390": "Men's",
  "420": "Men's 2",
  "458": "Men's 2",
  "604": "Women's",
  "615": "Men's",
  "630": "Lifestyle 2",
  "654": "Women's",
  "693": "Men's",
  "717": "Men's",
  "744": "Men's",
  "784": "Men's",
  "801": "Men's"
};

export const MOCKUP_STYLE_VIEWS: Record<string, Record<string, string>> = {
  "83": {
    "7225": "Front",
    "7226": "Back",
    "7227": "Front",
    "7228": "Back",
    "7229": "Front",
    "7230": "Back",
    "99475": "Front",
    "99496": "Back",
    "99502": "Front",
    "99504": "Back"
  },
  "257": {
    "963": "Front",
    "964": "Back",
    "965": "Right",
    "966": "Left",
    "7173": "Front",
    "7174": "Back",
    "27339": "Front",
    "27340": "Back",
    "27341": "Left"
  },
  "261": {
    "3437": "Front",
    "3438": "Back",
    "26024": "Front",
    "26025": "Back",
    "26305": "Front",
    "26306": "Back",
    "26307": "Right",
    "26308": "Left"
  },
  "274": {
    "1107": "Front",
    "1108": "Back",
    "1109": "Inside Pocket",
    "8645": "Front",
    "8646": "Product Details"
  },
  "320": {
    "2291": "Front",
    "2292": "Back",
    "2295": "Right Front",
    "2296": "Left Front",
    "11466": "Front",
    "11467": "Back",
    "14525": "Front",
    "14526": "Back",
    "14527": "Right Front",
    "14528": "Left Front",
    "51583": "Product Details 2"
  },
  "388": {
    "6307": "Front",
    "6308": "Back",
    "6309": "Right",
    "6310": "Left",
    "11462": "Front",
    "11463": "Back",
    "31581": "Back 2",
    "32479": "Product Details 2"
  },
  "390": {
    "6331": "Front",
    "6332": "Back",
    "6333": "Right",
    "6334": "Left",
    "13633": "Front",
    "13634": "Back",
    "54243": "Product Details"
  },
  "420": {
    "8020": "Front",
    "8021": "Back",
    "8022": "Folded",
    "8023": "On Tube",
    "8113": "Front",
    "8114": "Right",
    "8115": "Left",
    "8116": "Front",
    "8117": "Right",
    "8118": "Left"
  },
  "458": {
    "11615": "Front",
    "11617": "Back",
    "11618": "Right Front",
    "11619": "Left Front",
    "11620": "Top",
    "11621": "Inside",
    "11663": "Front",
    "11664": "Right Front",
    "11665": "Left Front",
    "11666": "Back",
    "11758": "Front",
    "11759": "Back",
    "11760": "Right Front",
    "11761": "Left Front"
  },
  "604": {
    "22364": "Front",
    "22368": "Back",
    "22443": "Front",
    "22444": "Back",
    "22445": "Front",
    "22446": "Back",
    "22453": "Right Front",
    "22481": "Left Front"
  },
  "615": {
    "22544": "Front",
    "22634": "Back",
    "22635": "Front",
    "22637": "Back",
    "22705": "Front 2",
    "22706": "Right",
    "23674": "Product Details"
  },
  "630": {
    "23262": "Front",
    "23276": "Front",
    "23280": "Front",
    "23346": "Product Details",
    "23347": "Product Details",
    "23348": "Product Details",
    "23355": "Front",
    "23356": "Front",
    "23357": "Front"
  },
  "654": {
    "26051": "Front Outside",
    "26052": "Back Outside",
    "26054": "Back Inside",
    "26111": "Product Details Outside",
    "26116": "Product Details Inside",
    "26127": "Right Front Outside",
    "26128": "Right Front Inside",
    "26155": "Front Outside",
    "26156": "Back Outside",
    "26157": "Right Front Outside",
    "26158": "Right Outside",
    "26159": "Front 2 Outside",
    "26161": "Back Inside",
    "26162": "Front Inside",
    "26163": "Front 2 Inside",
    "26164": "Right Inside",
    "26165": "Right Front Inside",
    "26176": "Front Outside",
    "26177": "Back Outside",
    "26178": "Left Front Outside",
    "26179": "Right Outside",
    "26180": "Back Inside",
    "26181": "Front Inside",
    "26182": "Left Front Inside",
    "26183": "Right Inside",
    "26200": "Right Inside",
    "26201": "Right Outside",
    "26226": "Front Inside"
  },
  "693": {
    "30425": "Front",
    "30426": "Back",
    "30428": "Product Details",
    "30430": "Product Details 2",
    "30435": "Front",
    "30436": "Back",
    "30438": "Left Front"
  },
  "717": {
    "32252": "Back",
    "32253": "Front",
    "32347": "Product Details",
    "32364": "Back",
    "32365": "Front"
  },
  "744": {
    "39513": "Back",
    "39520": "Front",
    "39539": "Product Details",
    "39560": "Product Details 2",
    "39574": "Front",
    "39575": "Front 2",
    "39576": "Front 3",
    "39628": "Product Details 3",
    "45262": "Product Details 4"
  },
  "784": {
    "51113": "Back",
    "51116": "Front",
    "51119": "Product Details",
    "51135": "Front",
    "51139": "Left",
    "51142": "Right Back",
    "51145": "Right Front"
  },
  "801": {
    "57206": "Back",
    "57214": "Front",
    "57252": "Back",
    "57260": "Front",
    "57268": "Product Details",
    "73655": "Product Details 2",
    "73663": "Product Details 3",
    "73671": "Product Details 4"
  }
};

export const PER_VARIANT_MOCKUP_PRODUCTS: string[] = [
  "83",
  "630"
];
