import React from 'react';
import PageContainer from '../components/ui/PageContainer';
import LegalSection from '../components/ui/LegalSection';
import { usePageMeta } from '../hooks/usePageMeta';

const SUPPORT = (
  <a className="text-interactive hover:underline" href="mailto:support@chromaforge.app">
    support@chromaforge.app
  </a>
);

function Item({ label, children }) {
  return (
    <li>
      <span className="text-text">{label}:</span> {children}
    </li>
  );
}

export default function PrivacyPage() {
  usePageMeta({
    title: 'Privacy Policy',
    description:
      "Chromaforge's privacy policy: what account, design, and order data is collected, what's public, who it's shared with, and your rights.",
    path: '/privacy'
  });
  return (
    <PageContainer title="Privacy Policy">
      <p className="text-xs text-text-muted">Last updated: October 10, 2026</p>

      {/* intro-skip AND intro-stagger: the cascade nests. This block opts out of being a
          single item in the page's own cascade (a dozen sections arriving as one slab was
          the thing being fixed) and becomes a container in its own right, so each
          LegalSection gets its own delay from the same nth-child rules -- no per-section
          index to hand-maintain as sections are added or reordered. See tailwind.css. */}
      <div className="intro-skip intro-stagger mt-8 space-y-8">
        <LegalSection title="Overview">
          <p>
            This page explains what information Chromaforge (chromaforge.app, operated by Aaron
            Ezra Sterczewski, who is responsible for your data) collects, why, what's public, and
            who it's shared with. We collect only what's needed to run the site and fulfill
            orders. We don't use analytics or advertising trackers, and we don't sell your
            personal information or share it for advertising.
          </p>
        </LegalSection>

        <LegalSection title="Information We Collect">
          <ul className="list-disc space-y-1 pl-5">
            <Item label="Account info">
              your email address and password (stored only in hashed form by our authentication
              provider), plus the username and display name you set. If you sign in with Google,
              we receive your Google email address and name, and use the name as your initial
              display name. We don't use your Google profile photo: every account gets an avatar
              generated by Chromaforge.
            </Item>
            <Item label="Your designs">
              the seed, colors, and settings needed to regenerate each design you save, its
              title, a thumbnail image, and, for animations, their playback settings. We also
              record which designs you like.
            </Item>
            <Item label="Product previews and print files">
              when you generate a product preview or place an order, images of your design are
              rendered and stored so Printful can use them.
            </Item>
            <Item label="Order info">
              your name, shipping address, and email, the products and options you ordered,
              prices paid, and order status. Payment card details are collected and processed
              directly by Stripe — we never see or store your full card number.
            </Item>
            <Item label="Messages">the contents of any email you send us.</Item>
            <Item label="Technical data">
              like most websites, our hosting and service providers keep logs that include your
              IP address, browser type, and the time of requests. Our sign-in forms are protected
              by Cloudflare Turnstile, which looks at browser and device signals to tell people
              from bots.
            </Item>
          </ul>
          <p>
            Designs you haven't saved, and the images and videos you download, are made in your
            browser and aren't sent to us — unless you save them, generate a product preview, or
            place an order.
          </p>
        </LegalSection>

        <LegalSection title="Stored on Your Device">
          <p>
            Our site doesn't set cookies. It uses your browser's local storage to keep you signed
            in, to remember your studio settings (palette, generator sliders, video and download
            preferences), to keep your 9 most recent designs so you can bring one back from the
            studio's Recent panel, and to cache product details and recent product previews so
            pages load faster. Your recent designs stay on your device and aren't sent to us. You
            can clear any of this in your browser settings, or with the studio's Reset button for
            its settings. Stripe's checkout page and Cloudflare Turnstile run on
            those providers' own services and may set their own cookies.
          </p>
        </LegalSection>

        <LegalSection title="What's Public">
          <p>
            Every design you save is published to the public gallery. Anyone visiting the site
            can see the design, its title, thumbnail, and like count, along with your display name
            (or username) and avatar, and can open, download, and order prints of it. If you
            signed in with Google, your display name starts out as your Google name — you can
            change it on your Account page. Your profile name and avatar, and which designs your
            account has liked, can also be read by anyone. Your email address, orders, and
            shipping details are never public.
          </p>
        </LegalSection>

        <LegalSection title="How We Use This Information">
          <ul className="list-disc space-y-1 pl-5">
            <li>To run your account: sign-in, saving and loading designs, likes, and the gallery.</li>
            <li>To generate product previews and print files, and to fulfill and support orders.</li>
            <li>
              To send service emails: account confirmation and password reset emails from us,
              payment receipts from Stripe, and shipping and tracking updates from Printful. We
              don't send marketing emails.
            </li>
            <li>To keep the site secure and prevent abuse, fraud, and automated sign-ups.</li>
            <li>To respond to your messages and meet legal obligations, such as tax records.</li>
          </ul>
          <p>
            If you're in the European Economic Area or the UK, we rely on these legal bases:
            performing our contract with you (your account and orders), our legitimate interests
            (security, fraud prevention, and running the public gallery), and legal obligations
            (tax and accounting records).
          </p>
        </LegalSection>

        <LegalSection title="Who We Share It With">
          <p>We share information only with the service providers that run Chromaforge:</p>
          <ul className="list-disc space-y-1 pl-5">
            <Item label="Supabase">hosts our database, authentication, and file storage.</Item>
            <Item label="Stripe">
              processes payments and collects your shipping address and email at checkout.
            </Item>
            <Item label="Printful">
              generates product previews from your artwork, and receives your name, shipping
              address, email, and print files to make and ship your order.
            </Item>
            <Item label="Fly.io">
              renders print-resolution files. It receives only the design itself, not who you
              are.
            </Item>
            <Item label="Hostinger">
              hosts the website and sends our account emails; our support mailbox is hosted there
              too.
            </Item>
            <Item label="Cloudflare">
              provides the Turnstile bot check on our sign-in, sign-up, and password reset forms.
            </Item>
            <Item label="Google">
              serves the site's fonts (so it receives your IP address when pages load), and
              handles sign-in if you choose "Continue with Google."
            </Item>
          </ul>
          <p>
            We may also disclose information if required by law, or to protect our rights or
            other people's safety. If Chromaforge is ever sold or transferred, your information
            would go to the new owner under this policy. We don't sell your personal information
            to anyone.
          </p>
        </LegalSection>

        <LegalSection title="Where Your Data Is Processed">
          <p>
            Chromaforge is run from the United States, and your information is processed in the
            United States and other countries where our providers operate. Where data protection
            law requires it, those providers use approved safeguards, such as standard
            contractual clauses, for international transfers.
          </p>
        </LegalSection>

        <LegalSection title="Data Retention &amp; Deletion">
          <ul className="list-disc space-y-1 pl-5">
            <li>
              Your account, profile, and saved designs are kept until you delete them. You can
              delete any design yourself from My Designs, which also deletes its thumbnail.
            </li>
            <li>
              Product preview images are deleted automatically after a few days, and print files
              after a day, unless they belong to an order.
            </li>
            <li>
              Order records, including shipping details, are kept as long as we need them for
              tax, accounting, and legal purposes, even after an account is deleted. A checkout
              you don't complete is closed automatically after 24 hours.
            </li>
            <li>Provider logs are kept according to each provider's own retention schedule.</li>
          </ul>
          <p>
            There's no self-serve "delete account" button yet — email {SUPPORT} to request
            deletion of your account and associated data, and we'll process it manually.
          </p>
        </LegalSection>

        <LegalSection title="Your Rights">
          <p>
            You can ask us for a copy of the personal information we hold about you, ask us to
            correct or delete it, or object to or ask us to restrict how we use it, by emailing{' '}
            {SUPPORT}. We'll respond within the time the law requires, and won't treat you
            differently for asking. If you're in the European Economic Area or the UK, you can
            also complain to your local data protection authority.
          </p>
          <p>
            California residents: we don't sell or share personal information as those terms are
            defined in California law. Because we don't track visitors across other websites, we
            don't respond differently to browser "Do Not Track" signals.
          </p>
        </LegalSection>

        <LegalSection title="Children's Privacy">
          <p>
            Chromaforge isn't directed at children under 13, and we don't knowingly collect
            personal information from them. If you believe a child has created an account,
            contact us and we'll delete it.
          </p>
        </LegalSection>

        <LegalSection title="Security">
          <p>
            We rely on Supabase and Stripe's security infrastructure for authentication, data
            storage, and payment processing, and limit who can read each kind of data. No online
            service can guarantee perfect security, but we take reasonable steps to protect your
            information.
          </p>
        </LegalSection>

        <LegalSection title="Changes to This Policy">
          <p>
            We'll update the "Last updated" date above whenever this policy changes, and if a
            change materially affects how we use your information, we'll make it clear on the
            site.
          </p>
        </LegalSection>

        <LegalSection title="Contact">
          <p>Questions about this policy or your data? {SUPPORT}.</p>
        </LegalSection>
      </div>
    </PageContainer>
  );
}
