/*
 * Export filenames: an astronomy/physics adjective + noun, plus 4 hex digits
 * (e.g. CoherentWavefront-1f3a). Used by DisplayCanvas for both the .jpg still and the
 * .mp4 animation export.
 *
 * Rules for adding words, so the pool stays usable:
 *  - ONE word, capitalized, no spaces or hyphens -- the two are concatenated directly.
 *  - Real astronomy, astrophysics, optics or particle-physics terminology. Not sci-fi, not
 *    mystical, not generic mechanics ('Torque', 'Velocity') -- the point is that a filename
 *    reads like it came off an observatory, and one loose word is what breaks that.
 *  - Never put the same word in BOTH arrays: it would then be able to pair with itself.
 *    'Quantum' used to be in both, which made 'QuantumQuantum' reachable; it is an adjective
 *    here now. Nothing is currently in both, so keep it that way.
 *  - A shared stem across the two arrays is fine and sometimes the point -- 'PlanetaryNebula',
 *    'SpiralGalaxy' and 'RadiantRadiance' are all reachable, and the first two are real terms.
 *  - Both arrays are sorted; keep them that way so a duplicate is easy to spot by eye.
 *
 * 110 adjectives x 109 nouns = 11,990 name stems,
 * x 65,536 hex suffixes = 785,776,640 filenames.
 */

const astroNouns = [
  'Accretion',
  'Albedo',
  'Aperture',
  'Aphelion',
  'Apogee',
  'Apsis',
  'Asterism',
  'Aurora',
  'Azimuth',
  'Boson',
  'Caustic',
  'Chromosphere',
  'Cluster',
  'Coalescence',
  'Comet',
  'Conjunction',
  'Continuum',
  'Convection',
  'Corona',
  'Cosmos',
  'Cryosphere',
  'Culmination',
  'Declination',
  'Diffraction',
  'Dispersion',
  'Eclipse',
  'Ecliptic',
  'Ejecta',
  'Element',
  'Energy',
  'Entropy',
  'Epoch',
  'Equinox',
  'Ergosphere',
  'Exosphere',
  'Fermion',
  'Field',
  'Filament',
  'Fluence',
  'Flux',
  'Fusion',
  'Galaxy',
  'Gluon',
  'Graviton',
  'Gravity',
  'Halo',
  'Heliopause',
  'Heliosphere',
  'Horizon',
  'Hypernova',
  'Inclination',
  'Ionosphere',
  'Irradiance',
  'Isotope',
  'Libration',
  'Luminosity',
  'Magnetar',
  'Magnetosphere',
  'Magnitude',
  'Mantle',
  'Maser',
  'Meridian',
  'Meteor',
  'Nadir',
  'Nebula',
  'Neutrino',
  'Nova',
  'Nucleus',
  'Nutation',
  'Occultation',
  'Opacity',
  'Opposition',
  'Orbit',
  'Parallax',
  'Penumbra',
  'Perigee',
  'Perihelion',
  'Photon',
  'Photosphere',
  'Planet',
  'Plasma',
  'Positron',
  'Precession',
  'Prominence',
  'Protostar',
  'Pulsar',
  'Quark',
  'Quasar',
  'Radiance',
  'Reionization',
  'Resonance',
  'Scintillation',
  'Singularity',
  'Solstice',
  'Spectrum',
  'Star',
  'Supernova',
  'Syzygy',
  'Trajectory',
  'Transit',
  'Turbulence',
  'Twilight',
  'Umbra',
  'Vacuum',
  'Void',
  'Vortex',
  'Wavefront',
  'Wavelength',
  'Zenith'
];

const astroAdj = [
  'Absolute',
  'Achromatic',
  'Adiabatic',
  'Anisotropic',
  'Antimatter',
  'Ascending',
  'Axial',
  'Ballistic',
  'Barycentric',
  'Baryonic',
  'Binary',
  'Blueshift',
  'Bolometric',
  'Cavus',
  'Celestial',
  'Cepheid',
  'Chaotic',
  'Chromatic',
  'Circumpolar',
  'Coherent',
  'Collapsed',
  'Collimated',
  'Cosmic',
  'Cryogenic',
  'Crystalline',
  'Dark',
  'Degenerate',
  'Diffuse',
  'Dilated',
  'Doppler',
  'Eccentric',
  'Electromagnetic',
  'Elliptical',
  'Entangled',
  'Equatorial',
  'Ergodic',
  'Extragalactic',
  'Fluorescent',
  'Fused',
  'Galactic',
  'Geodesic',
  'Geosynchronous',
  'Globular',
  'Gravitational',
  'Harmonic',
  'Heliocentric',
  'Holographic',
  'Hyperbolic',
  'Hyperfine',
  'Incandescent',
  'Inertial',
  'Infrared',
  'Interstellar',
  'Ionized',
  'Iridescent',
  'Irregular',
  'Isothermal',
  'Isotropic',
  'Jovian',
  'Kinetic',
  'Lenticular',
  'Luminous',
  'Magnetic',
  'Meridional',
  'Molecular',
  'Monochromatic',
  'Nebular',
  'Neutron',
  'Nuclear',
  'Opalescent',
  'Optical',
  'Orbital',
  'Oscillating',
  'Parabolic',
  'Perturbed',
  'Photonic',
  'Planetary',
  'Polarized',
  'Primordial',
  'Prismatic',
  'Quantum',
  'Quiescent',
  'Radiant',
  'Radiative',
  'Redshift',
  'Refracted',
  'Relativistic',
  'Retrograde',
  'Rotational',
  'Scattered',
  'Sidereal',
  'Solar',
  'Spectral',
  'Spiral',
  'Stellar',
  'Stochastic',
  'Subatomic',
  'Subluminal',
  'Supergiant',
  'Superluminal',
  'Supersonic',
  'Synchrotron',
  'Terrestrial',
  'Thermal',
  'Tidal',
  'Toroidal',
  'Transient',
  'Ultraviolet',
  'Virial',
  'Zodiacal'
];

export default function FileName() {
  let name =
    astroAdj[Math.floor(Math.random() * astroAdj.length)] +
    astroNouns[Math.floor(Math.random() * astroNouns.length)];
  const hex = Math.floor(Math.random() * 0xffff).toString(16).padStart(4, '0');

  name += '-' + hex;

  return name;
}
